In [37]:
import numpy as np

x = np.array([[2,2,2],
              [2,3,4],
              [6,1,1]])
print(x.mean(0))

[ 3.33333333  2.          2.33333333]


In [43]:
import numpy as np, os

data = np.loadtxt(fname = "data\inflammation-01.csv", delimiter = ',')

print(os.getcwd())
print(data)
print(type(data))
print(data.shape)

print(data[0,2])
print(data[0:4, 0:10])

print(data.mean())

print('maximum inflammation:', data.max())
print('minimum inflammation:', data.min())
print('standard deviation:', data.std())

patient_0 = data[0, :]
print(patient_0)
print(patient_0.max())

import matplotlib.pyplot
image = matplotlib.pyplot.imshow(data)
matplotlib.pyplot.show(image)

C:\Users\HPDEMO\Documents\BoiseState_SciComp_Workshop\Software_Carpentry
[[ 0.  0.  1. ...,  3.  0.  0.]
 [ 0.  1.  2. ...,  1.  0.  1.]
 [ 0.  1.  1. ...,  2.  1.  1.]
 ..., 
 [ 0.  1.  1. ...,  1.  1.  1.]
 [ 0.  0.  0. ...,  0.  2.  0.]
 [ 0.  0.  1. ...,  1.  1.  0.]]
<class 'numpy.ndarray'>
(60, 40)
1.0
[[ 0.  0.  1.  3.  1.  2.  4.  7.  8.  3.]
 [ 0.  1.  2.  1.  2.  1.  3.  2.  2.  6.]
 [ 0.  1.  1.  3.  3.  2.  6.  2.  5.  9.]
 [ 0.  0.  2.  0.  4.  2.  2.  1.  6.  7.]]
6.14875
maximum inflammation: 20.0
minimum inflammation: 0.0
standard deviation: 4.61383319712
[  0.   0.   1.   3.   1.   2.   4.   7.   8.   3.   3.   3.  10.   5.   7.
   4.   7.   7.  12.  18.   6.  13.  11.  11.   7.   7.   4.   6.   8.   8.
   4.   4.   5.   7.   3.   4.   2.   3.   0.   0.]
18.0
None


#"If variables are nouns, methods are verbs: they are what the thing in question knows how to do."